export default function TermsPage() {
  return (
    <div className="min-h-screen" style={{ background: '#0A0A0B' }}>
      <nav className="flex items-center justify-between px-4 sm:px-8 py-4 sm:py-5">
        <a href="/" className="flex items-center gap-2.5">
          <div className="w-7 h-7 rounded-lg" style={{ background: 'linear-gradient(135deg, #FF3B5C, #FF6B81)' }} />
          <span className="font-extrabold text-lg" style={{ color: '#F0F0F2' }}>TrendMatch</span>
        </a>
      </nav>
      <div className="max-w-2xl mx-auto px-4 sm:px-8 py-12">
        <h1 className="text-3xl font-extrabold mb-8" style={{ color: '#F0F0F2' }}>Terms of Service</h1>
        <div className="space-y-6 text-sm" style={{ color: '#8A8A96', lineHeight: 1.8 }}>
          <p><strong style={{ color: '#F0F0F2' }}>Last Updated:</strong> March 1, 2026</p>

          <div>
            <h2 className="text-base font-bold mb-2" style={{ color: '#F0F0F2' }}>1. Acceptance of Terms</h2>
            <p>By accessing or using TrendMatch ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.</p>
          </div>

          <div>
            <h2 className="text-base font-bold mb-2" style={{ color: '#F0F0F2' }}>2. Description of Service</h2>
            <p>TrendMatch is an AI-powered product intelligence platform that analyzes TikTok creator profiles to generate product recommendations for TikTok Shop. The Service provides product suggestions, estimated pricing, margin calculations, and content ideas based on AI analysis.</p>
          </div>

          <div>
            <h2 className="text-base font-bold mb-2" style={{ color: '#F0F0F2' }}>3. TikTok Account Access</h2>
            <p>When you connect your TikTok account, we access your public profile information, follower statistics, and recent video data through TikTok's official API with read-only permissions. We never post content on your behalf, modify your account, or access private messages.</p>
          </div>

          <div>
            <h2 className="text-base font-bold mb-2" style={{ color: '#F0F0F2' }}>4. AI-Generated Recommendations</h2>
            <p>Product recommendations, pricing estimates, and margin calculations are generated by AI and are provided for informational purposes only. TrendMatch does not guarantee the accuracy of pricing, product availability, supplier reliability, or profitability of any recommended products. Users are responsible for conducting their own due diligence before making purchasing or selling decisions.</p>
          </div>

          <div>
            <h2 className="text-base font-bold mb-2" style={{ color: '#F0F0F2' }}>5. User Accounts</h2>
            <p>You are responsible for maintaining the security of your account. Free accounts are limited to one product analysis per month. Paid subscriptions provide additional features as described on our pricing page. We reserve the right to suspend or terminate accounts that violate these terms.</p>
          </div>

          <div>
            <h2 className="text-base font-bold mb-2" style={{ color: '#F0F0F2' }}>6. Intellectual Property</h2>
            <p>The Service, including its design, code, AI models, and content, is owned by TrendMatch. Product recommendations generated for you are yours to use freely for your business purposes.</p>
          </div>

          <div>
            <h2 className="text-base font-bold mb-2" style={{ color: '#F0F0F2' }}>7. Limitation of Liability</h2>
            <p>TrendMatch is provided "as is" without warranties of any kind. We are not liable for any losses, damages, or costs arising from your use of the Service, including but not limited to business decisions made based on AI-generated recommendations.</p>
          </div>

          <div>
            <h2 className="text-base font-bold mb-2" style={{ color: '#F0F0F2' }}>8. Changes to Terms</h2>
            <p>We may update these terms at any time. Continued use of the Service after changes constitutes acceptance of the updated terms.</p>
          </div>

          <div>
            <h2 className="text-base font-bold mb-2" style={{ color: '#F0F0F2' }}>9. Contact</h2>
            <p>For questions about these terms, contact us at <a href="mailto:sleighdesmond@gmail.com" style={{ color: '#FF3B5C' }}>sleighdesmond@gmail.com</a>.</p>
          </div>
        </div>
      </div>
    </div>
  )
}
